### ISSUE TITLE
Long list items causes flicker - Not fixed

### ISSUE THREAD

**Issue by n00bz0rd2** [senchalabs/jQTouch#194]
I'm pretty new to jQTouch, but loving it so far. One thing I have noticed though is if I have a list with 20 items or more, navigating to and from that list causes a black flicker. The flicker doesn't happen all of the time but it happens more often than not. Say 90% of the time. This occurs on both the device and simulator.

Anyone else had this problem or have a fix?

**Comment by zander-berg** [comment]
Hey guys,

since my application contains rather long lists, I am also having this problem and devised the following nasty workaround:

Before you start the animation, cut off the list to be small enough to make the animation go smoothly yet large enough s.th. the user does not notice it has been truncated (I realize that this may be problematic if your target device does not have a fixed screen size). Then set up a timeout that adds the missing part to the list after the animation has finished.

This was relatively easy to implement with my specific app, since the content is database-generated. However, a fix would still be greatly appreciated, as the code looks rather ugly now.
